<img src="./images/python.png">

<h1>Hitchhiker's Guide to Data Science: Python</h1>

<div style="background-color:#F2F2F2; width:50%">
<h2>Table of contents</h2>
<ol style="font-family: 'Raleway', Arial, sans-serif; font-weight: 400; font-size: 15px;" start="11">
    <li> <strong> Types of Operator </strong> </li>
        <ul style="list-style-type: circle; margin-top:0">
            <li> Arithmetic Operators </li>
            <li> Comparison Operators </li>
            <li> Assignment Operators </li>
            <li> Logical Operators </li>
            <li> Membership Operators </li>
            <li> Python Operators Precedence </li>
        </ul>
</ol>
</div>

<h2 style="color:#045FB4">Types of Operator</h2>

<div class="alert alert-info">
Operators are the constructs, which can manipulate the value of operands. Consider the expression 4 + 5 = 9. Here, 4 and 5 are called the operands and + is called the operator.
</div>

<h3 style="color:#8A0808">Arithmetic Operators</h3>

<table class="table table-bordered">
    <tr>
        <th style="width:10%">Operator</th>
        <th style="width:45%">Description</th>
    <th>Example</th>
    </tr>
    <tr>
        <td>+ Addition</td>
        <td>Adds values on either side of the operator.</td>
        <td>a + b = 30</td>
    </tr>
    <tr>
        <td>- Subtraction</td>
        <td>Subtracts right hand operand from left hand operand.</td>
        <td>a â€“ b = -10</td>
    </tr>
    <tr>
        <td>\* Multiplication</td>
        <td>Multiplies values on either side of the operator</td>
        <td>a \* b = 200</td>
    </tr>
    <tr>
        <td>/ Division</td>
        <td>Divides left hand operand by right hand operand</td>
        <td>b / a = 2</td>
    </tr>
    <tr>
        <td>% Modulus</td>
        <td>Divides left hand operand by right hand operand and returns remainder</td>
        <td>b % a = 0</td>
    </tr>
    <tr>
        <td>\*\* Exponent</td>
        <td>Performs exponential (power) calculation on operators</td>
        <td>a\*\*b =10 to the power 20</td>
    </tr>
    <tr>
        <td>//</td>
        <td>Floor Division - The division of operands where the result is the quotient in which the digits after the decimal point are removed. But if one of the operands is negative, the result is floored, i.e., rounded away from zero (towards negative infinity):</td>
        <td>9//2 = 4 and 9.0//2.0 = 4.0, -11//3 = -4, -11.0//3 = -4.0</td>
    </tr>
</table>

<h4>Example:</h4>

In [2]:
a = 25
b = 5
c = 0
print("a = ", a, end=", ")
print("b = ", b, end=", ")
print("c = ", c)
print()
c = a + b
print("c = a + b is ", c)

c = a - b
print("c = a - b is ", c) 

c = a * b
print("c = a * b is ", c) 

c = a / b
print("c = a / b is ", c) 

c = a % b
print("c = a % b is ", c)

a = 2
b = 3
print()
print("a = ", a, end=", ")
print("b = ", b)
print()
c = a**b 
print("c = a**b is ", c)

a = 11
b = 5
print()
print("a = ", a, end=", ")
print("b = ", b)
print()
c = a//b 
print("c = a//b is ", c)

a =  25, b =  5, c =  0

c = a + b is  30
c = a - b is  20
c = a * b is  125
c = a / b is  5.0
c = a % b is  0

a =  2, b =  3

c = a**b is  8

a =  11, b =  5

c = a//b is  2

<h3 style="color:#8A0808">Comparison Operators</h3>
<p>These operators compare the values on either sides of them and decide the relation among them. They are also called Relational operators.</p>

<table class="table table-bordered">
    <tr>
        <th style="width:10%">Operator</th><th style="width:45%">Description</th><th>Example</th>
    </tr>
    <tr>
        <td>==</td>
        <td>If the values of two operands are equal, then the condition becomes true.</td>
        <td> (a == b) is not true.</td>
    </tr>
    <tr>
        <td>!=</td>
        <td>If values of two operands are not equal, then condition becomes true.</td>
        <td> (a &lt;&gt; b) is true. This is similar to != operator.</td>
    </tr>
    <tr>
        <td>&gt;</td>
        <td>If the value of left operand is greater than the value of right operand, then condition becomes true.</td>
        <td> (a &gt; b) is not true.</td>
    </tr>
    <tr>
        <td>&lt;</td>
        <td>If the value of left operand is less than the value of right operand, then condition becomes true.</td>
        <td> (a &lt; b) is true.</td>
    </tr>
    <tr>
        <td>&gt;=</td>
        <td>If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.</td>
        <td> (a &gt;= b) is not true. </td>
    </tr>
    <tr>
        <td>&lt;=</td>
        <td>If the value of left operand is less than or equal to the value of right operand, then condition becomes true.</td>
        <td> (a &lt;= b) is true. </td>
    </tr>
</table>

<h4>Example:</h4>

In [3]:
a = 25
b = 5
c = 0

print("a = ", a, end=", ")
print("b = ", b, end=", ")
print("c = ", c)
print()

if ( a == b ):
    print("Comparison 1 - a is equal to b")
else:
    print("Comparison 1 - a is not equal to b")

if ( a != b ):
    print("Comparison 2 - a is not equal to b")
else:
    print("Comparison 2 - a is equal to b")
    
if ( a < b ):
    print("Comparison 3 - a is less than b" )
else:
    print("Comparison 3 - a is not less than b")

if ( a > b ):
    print("Comparison 4 - a is greater than b")
else:
    print("Comparison 4 - a is not greater than b")

a = 5;
b = 20;


print("\na = ", a, end=", ")
print("b = ", b)
print()

if ( a <= b ):
    print("Comparison 5 - a is either less than or equal to  b")
else:
    print("Comparison 5 - a is neither less than nor equal to  b")

if ( a >= b ):
    print("Comparison 6 - a is either greater than  or equal to b")
else:
    print("Comparison 6 - a is neither greater than  nor equal to b")

a =  25, b =  5, c =  0

Comparison 1 - a is not equal to b
Comparison 2 - a is not equal to b
Comparison 3 - a is not less than b
Comparison 4 - a is greater than b

a =  5, b =  20

Comparison 5 - a is either less than or equal to  b
Comparison 6 - a is neither greater than  nor equal to b

<h3 style="color:#8A0808">Assignment Operators</h3>
<table class="table table-bordered">
    <tr>
        <th style="width:10%">Operator</th>
        <th style="width:45%">Description</th>
        <th>Example</th>
    </tr>
    <tr>
        <td>=</td>
        <td>Assigns values from right side operands to left side operand</td>
        <td>c = a + b assigns value of a + b into c</td>
    </tr>
    <tr>
        <td>+=
        Add AND</td>
        <td>It adds right operand to the left operand and assign the result to left operand</td>
        <td>c += a is equivalent to c = c + a</td>
    </tr>
    <tr>
        <td>-=
        Subtract AND</td>
        <td>It subtracts right operand from the left operand and assign the result to left operand</td>
        <td>c -= a is equivalent to c = c - a</td>
    </tr>
    <tr>
        <td>\*=
        Multiply AND</td>
        <td>It multiplies right operand with the left operand and assign the result to left operand</td>
        <td>c \*= a is equivalent to c = c \* a</td>
    </tr>
    <tr>
        <td>/=
        Divide AND</td>
        <td>It divides left operand with the right operand and assign the result to left operand</td>
        <td>c /= a is equivalent to c = c / ac /= a is equivalent to c = c / a</td>
    </tr>
    <tr>
        <td>%=
        Modulus AND</td>
        <td>It takes modulus using two operands and assign the result to left operand</td>
        <td>c %= a is equivalent to c = c % a</td>
    </tr>
    <tr>
        <td>\*\*=
        Exponent AND</td>
        <td>Performs exponential (power) calculation on operators and assign value to the left operand</td>
        <td>c \*\*= a is equivalent to c = c \*\* a</td>
    </tr>
    <tr>
        <td>//=
        Floor Division</td>
        <td>It performs floor division on operators and assign value to the left operand</td>
        <td>c //= a is equivalent to c = c // a</td>
    </tr>
</table>

<h4>Example:</h4>

In [7]:
a = 4
b = 5
c = 0

print("a = ", a, end=", ")
print("b = ", b, end=", ")
print("c = ", c)
print()

c = a + b
print("c = a + b is ", c)

c += a
print("c += a is ", c)

c *= a
print("c *= a is ", c)

c /= a 
print("c /= a is ", c)

c = 2
print("\nc = ", c)
print()

c %= a
print("c %= a is ", c)

c **= a
print("c **= a is ", c)

c //= a
print("c //= a is ", c)

a =  4, b =  5, c =  0

c = a + b is  9
c += a is  13
c *= a is  52
c /= a is  13.0

c =  2

c %= a is  2
c **= a is  16
c //= a is  4

<h3 style="color:#8A0808">Logical Operators</h3>
<p>There are following logical operators supported by Python language. Assume variable a holds 10 and variable b holds 20 then</p>
<table class="table table-bordered">
    <tr>
        <th style="width:10%">Operator</th>
        <th style="width:45%">Description</th>
        <th>Example</th>
    </tr>
    <tr>
        <td>and
        Logical AND</td>
        <td>If both the operands are true then condition becomes true.</td>
        <td>(a and b) is true.</td>
    </tr>
    <tr>
        <td>or
        Logical OR</td>
        <td>If any of the two operands are non-zero then condition becomes true.</td>
        <td> (a or b) is true.</td>
    </tr>
    <tr>
        <td>not
        Logical NOT</td>
        <td>Used to reverse the logical state of its operand.</td>
        <td>Not(a and b) is false. </td>
    </tr>
</table>

<h4>Example:</h4>

In [9]:
a = True
b = False
c = True

print(a, "AND", c ,"---", a and c) #True
print(a, "AND", b ,"---", a and b) #False

print(a, "OR", b ,"---", a or b) #True

print("NOT", a ,"---", not a) #False
print("NOT", b ,"---", not b) #True

True AND True --- True
True AND False --- False
True OR False --- True
NOT True --- False
NOT False --- True

<h3 style="color:#8A0808">Membership Operators</h3>

<p>Pythonâ€™s membership operators test for membership in a sequence, such as strings, lists, or tuples.</p>

<table class="table table-bordered">
    <tr>
        <th style="width:10%">Operator</th><th style="width:45%">Description</th><th>Example</th>
    </tr>
    <tr>
        <td>in</td>
        <td>Evaluates to true if it finds a variable in the specified sequence and false otherwise.</td>
        <td>x in y, here in results in a 1 if x is a member of sequence y.</td>
    </tr>
    <tr>
        <td>not in</td>
        <td>Evaluates to true if it does not finds a variable in the specified sequence and false otherwise.</td>
        <td>x not in y, here not in results in a 1 if x is not a member of sequence y.</td>
    </tr>
</table>

<h4>Example:</h4>

In [10]:
a = 10
b = 20
list = [1, 2, 3, 4, 5 ];

print("List:", list)
print()


if ( a in list ):
    print(a, "is in the list")
else:
    print(a, "is not in the list")

if ( b not in list ):
    print(b, "is not in the list")
else:
    print(b, "is in the list")

a = 2
if ( a in list ):
    print(a, "is in the list")
else:
    print(a, "is not in the list")

List: [1, 2, 3, 4, 5]

10 is not in the list
20 is not in the list
2 is in the list

<h3 style="color:#8A0808">Python Operators Precedence</h3>
<br>
<div class="alert alert-info">
The table lists all operators **from highest precedence to lowest**.
</div>

<table  class="table table-bordered">
    <tr>
        <th>Operator</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>\*\*</td>
        <td>Exponentiation (raise to the power)</td>
    </tr>
    <tr>
        <td>~ + -</td>
        <td>Complement, unary plus and minus (method names for the last two are +@ and -@)</td>
    </tr>
    <tr>
        <td>* / % //</td>
        <td>Multiply, divide, modulo and floor division</td>
    </tr>
    <tr>
        <td>+ -</td>
        <td>Addition and subtraction</td>
    </tr>
    <tr>
        <td>&gt;&gt; &lt;&lt;</td>
        <td>Right and left bitwise shift</td>
    </tr>
    <tr>
        <td>&amp;</td>
        <td>Bitwise 'AND'</td>
    </tr>
    <tr>
        <td>^ |</td>
        <td>Bitwise exclusive `OR' and regular `OR'</td>
    </tr>
    <tr>
        <td>&lt;= &lt; &gt; &gt;=</td>
        <td>Comparison operators</td>
    </tr>
    <tr>
        <td>&lt;&gt; == !=</td>
        <td>Equality operators</td>
    </tr>
    <tr>
        <td>= %= /= //= -= += *= **=</td>
        <td>Assignment operators</td>
    </tr>
    <tr>
        <td>is is not</td>
        <td>Identity operators</td>
    </tr>
    <tr>
        <td>in not in</td>
        <td>Membership operators</td>
    </tr>
    <tr>
        <td>not or and</td>
        <td>Logical operators</td>
    </tr>
</table>

<h4>Example:</h4>

In [11]:
a = 20
b = 10
c = 15
d = 5
e = 0

e = (a + b) * c / d       #( 30 * 15 ) / 5
print("Value of (a + b) * c / d is ",  e)

e = ((a + b) * c) / d     # (30 * 15 ) / 5
print("Value of ((a + b) * c) / d is ",  e)

e = (a + b) * (c / d);    # (30) * (15/5)
print("Value of (a + b) * (c / d) is ",  e)

e = a + (b * c) / d;      #  20 + (150/5)
print("Value of a + (b * c) / d is ",  e)

Value of (a + b) * c / d is  90.0
Value of ((a + b) * c) / d is  90.0
Value of (a + b) * (c / d) is  90.0
Value of a + (b * c) / d is  50.0